config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'users' => 'users#index'

  post 'friendships' => 'friendships#create'
  delete 'friendships/:id' => 'friendships#destroy'

  get 'messages/sent' => 'messages#sent'
  resources :messages

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  def is_read
    self.read_at.present? ? true : false
  end

  def read_info
    self.read_at.present? ? self.read_at.to_formatted_s(:long_ordinal) : "Unread"
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  has_secure_password

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  def sent_messages
    Message.where(sender: self)
  end

  def received_messages
    Message.where(recipient: self)
  end

  def recent_messages(n = 10)
    received_messages.order(created_at: :desc).limit(n)
  end

  def is_friend(id)
    Friendship.where(user_id: id, friend_id: self.id).first
  end

  def non_friends
    User.where.not(id: friend_ids).where.not(id: self.id)
  end

  def recent_non_friends(n = 10)
    User.where.not(id: friend_ids).where.not(id: self.id).order(created_at: :desc).limit(n)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper ApplicationHelper
  protect_from_forgery with: :exception

  protected

  def current_user
    helpers.current_user
  end

  def require_user!
    unless current_user
      redirect_to login_path, flash: {error: "Only authorized users could have access. Please log in."}
    end
  end

  def public_only!
    if current_user
      redirect_to root_path, flash: {notice: "Already logged in. "}
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:success] = 'Added new friend successfully'
    else
      flash[:error] = 'Cant save data, Please have a look'
    end
    redirect_to(:back)
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."

    redirect_to(:back)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user

      @messages = current_user.recent_messages
      @new_users = current_user.recent_non_friends

      render 'auth'
    else
      render 'public'
    end
  end

  def public
  end

  def auth
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user!

  def index
    redirect_to root_path
  end

  def show
    @message = Message.find(params[:id])

    if current_user.id != @message.recipient_id
      flash[:error] = "Sorry, you're not allow to read this"
      redirect_to root_path
    else
      if @message.read_at == nil
        @message.read_at = Time.now
        @message.save
      else
        flash[:notice] = 'You already read this message at ' + @message.read_at.to_formatted_s(:long_ordinal)
        redirect_to root_path
      end
    end
  end

  def new
    @message = Message.new({sender_id: current_user.id})
    @friends = current_user.friends
  end

  def create
    @message = Message.new(message_params)
    @message.sender_id = current_user.id
    @friends = current_user.friends

    if @message.save
      flash[:success] = 'Message sent successfully.'
      redirect_to root_path
    else
      flash[:error] = 'Unable to save message.'
      render 'new'
    end
  end

  def sent
    @messages = current_user.sent_messages.order(created_at: :desc)
  end

  def recieved
    @messages = current_user.recieved_messages.order(created_at: :desc)
  end

  private
  def message_params
    params.require(:message).permit(:recipient_id, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # show login
  def new
    @user = User.new
  end

  # do login
  def create
    if @user = User.find_by_email(params[:email])
      if @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:success] = 'Login successfully!'
        redirect_to root_path
      else
        flash[:error] = 'Incorrect password'
        render 'new'
      end
    else
      flash[:error] = 'User not found with email ' + params[:email]
      render 'new'
    end
  end

  # do logout
  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logout successfully!'
    redirect_to root_path
  end

  private
  def session_params
    params.require(:user).premit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # signup form
  def new
      @user = User.new
  end

  # do signup
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User registered successfully'
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = 'Invalid data. Check your inputs'
      render 'new'
    end
  end

  # list of users
  def index
    @users = User.where.not(id: current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, message, class: "alert alert-dismissible #{bootstrap_class_for(msg_type)} fade in") do
        content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
      end
    end.join.html_safe
  end

  def current_user
    return @current_user if @current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/auth.html.erb
<h3>Welcome to GauCHAT</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae eum architecto cum dolor
animi saepe, nesciunt numquam velit mollitia, recusandae corporis in, quo voluptate optio dicta
porro voluptas sequi, earum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>
Molestiae eum architecto cum dolor animi saepe, nesciunt numquam velit mollitia, recusandae corporis
in, quo voluptate optio dicta porro voluptas sequi, earum.</p>

<hr>

<!-- Buttons -->
<p class="text-right">
  <%= link_to 'New Message', new_message_path, class: "btn btn-primary" %>
  &nbsp;
  <%= link_to 'Add Friends', users_path, class: "btn btn-info" %>
  &nbsp;
  <%= link_to 'Sent Messages', messages_sent_path, class: "btn btn-warning" %>
</p>

<!-- Recently messages -->
<div class="panel panel-primary">
  <div class="panel-heading">Recently messages</div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Sender</th>
          <th>Send at</th>
          <th>Read at</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @messages.each do |message| %>
          <tr class="<%= message.is_read ? "" : "warning" %>">
            <td><%= message.sender.email %></td>
            <td><%= message.created_at.to_formatted_s(:long_ordinal) %></td>
            <td><%= message.read_info %></td>
            <td>
              <% if !message.is_read %>
                <%= link_to 'Show', message, class: "btn btn-info btn-sm" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- Recently users -->
<div class="panel panel-primary">
  <div class="panel-heading">Recently registered users</div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Email</th>
          <th>Registered at</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @new_users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= user.created_at.to_formatted_s(:long_ordinal) %></td>
            <td>
              <%= link_to "Add Friend", friendships_path(:friend_id => user),
                method: "post",
                class: "btn btn-info btn-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
      <img src="https://www.constant-content.com/blog/wp-content/uploads/2016/04/1200x700-2.jpg" alt="">
      <div class="carousel-caption">
        <h3>Thumbnail label</h3>
        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec.</p>
      </div>
    </div>
    <div class="item">
      <img src="http://www.ledapalermo.com/wp-content/uploads/2015/06/d6e1802f3d3780ad57eebf2a757bd164-1200x700.png" alt="" />
      <div class="carousel-caption">
        <h3>Thumbnail label</h3>
        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec.</p>
      </div>
    </div>
    <div class="item">
      <img src="http://mjsvirtual.com.au/wp/wp-content/uploads/2016/03/cropped-VA-slider-1200x700.jpg" alt="">
      <div class="carousel-caption">
        <h3>Thumbnail label</h3>
        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec.</p>
      </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control fui-arrow-left left" href="#myCarousel" data-slide="prev"></a>
  <a class="carousel-control fui-arrow-right right" href="#myCarousel" data-slide="next"></a>
</div>

<hr>

<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h2>
<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
<strong>Donec ullamcorper</strong> nulla non metus auctor fringilla. Duis mollis, est non commodo
luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
<blockquote>
  <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ullamcorper nulla non metus auctor fringilla. Duis mollis, est non commodo luctus.</p>
  <small>Someone famous, Big company</small>
</blockquote>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p class="lead">Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>

app/views/home/public.html.erb
<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
      <img src="https://www.constant-content.com/blog/wp-content/uploads/2016/04/1200x700-2.jpg" alt="">
      <div class="carousel-caption">
        <h3>Thumbnail label</h3>
        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec.</p>
      </div>
    </div>
    <div class="item">
      <img src="http://www.ledapalermo.com/wp-content/uploads/2015/06/d6e1802f3d3780ad57eebf2a757bd164-1200x700.png" alt="" />
      <div class="carousel-caption">
        <h3>Thumbnail label</h3>
        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec.</p>
      </div>
    </div>
    <div class="item">
      <img src="http://mjsvirtual.com.au/wp/wp-content/uploads/2016/03/cropped-VA-slider-1200x700.jpg" alt="">
      <div class="carousel-caption">
        <h3>Thumbnail label</h3>
        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec.</p>
      </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control fui-arrow-left left" href="#myCarousel" data-slide="prev"></a>
  <a class="carousel-control fui-arrow-right right" href="#myCarousel" data-slide="next"></a>
</div>

<hr>

<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h2>
<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
<strong>Donec ullamcorper</strong> nulla non metus auctor fringilla. Duis mollis, est non commodo
luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
<blockquote>
  <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ullamcorper nulla non metus auctor fringilla. Duis mollis, est non commodo luctus.</p>
  <small>Someone famous, Big company</small>
</blockquote>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p class="lead">Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gauchat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-embossed navbar-sitemenu" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-03">
            <span class="sr-only">Toggle navigation</span>
          </button>
          <%= link_to 'GauCHAT', root_path, class: 'navbar-brand'  %>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-03">

          <ul class="nav navbar-nav">
            <% if !current_user %>
              <li class="<%= current_page?(login_path) ? 'active' : '' %>">
                <%= link_to 'Login', 'login'  %>
              </li>
              <li class="<%= current_page?(signup_path) ? 'active' : '' %>">
                <%= link_to 'Sign Up', 'signup'  %>
              </li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                  <%= current_user.email %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- <li><%= link_to 'My Inbox', 'inbox' %></li>
                  <li><%= link_to 'My Friends', 'friends' %></li>
                  <li role="separator" class="divider"></li> -->
                  <li><%= link_to 'Logout', 'logout', method: 'delete' %></li>
                </ul>
              </li>
            <% end %>
           </ul>

        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <%= flash_messages %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/messages/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">New Message</div>
  <div class="panel-body">

    <% if @message.errors.any? %>
      <div class="alert alert-danger">
        <h4>Error: Invalid data. Check your inputs.</h4>
        <ul>
          <% @message.errors.full_messages.each do |thing| %>
            <li><%= thing %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for @message do |f| %>
      <div class="form-group">
        <label for="message_recipient">Recipient</label>
        <%= f.collection_select(:recipient_id, @friends, :id, :email,
          {:include_blank => 'Select friend as recipient...'},
          {:class => 'form-control'}) %>
      </div>

      <div class="form-group">
        <label for="message_body">Body</label>
        <%= f.text_area :body, class: "form-control", id: "message_body" %>
      </div>

      <div class="form-group form-actions text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    <% end %>

  </div>
</div>

app/views/messages/sent.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Sent messages</div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Recipient</th>
          <th>Send at</th>
          <th>Read at</th>
        </tr>
      </thead>
      <tbody>
        <% @messages.each do |message| %>
          <tr class="<%= message.is_read ? "" : "warning" %>">
            <td><%= message.recipient.email %></td>
            <td><%= message.created_at.to_formatted_s(:long_ordinal) %></td>
            <td><%= message.read_info %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/messages/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Message Detail</div>
  <div class="panel-body">

    <table class="table table-bordered">
      <tr>
        <td class="text-uppercase"><strong>Sender</strong></td>
        <td><%= @message.sender.email %></td>
      </tr>
      <tr>
        <td class="text-uppercase"><strong>Sent at</strong></td>
        <td><%= @message.created_at.to_formatted_s(:long_ordinal) %></td>
      </tr>
    </table>

    <hr>
    <div><%= @message.body %></div>

    <br>

  </div>
</div>

app/views/users/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Users</div>
  <div class="panel-body">
    <table class="table table-hover">
          <thead>
            <tr>
              <th>Email</th>
              <th>Register At</th>
              <th>Total Friends</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.email %></td>
                <td><%= user.created_at.to_formatted_s(:long_ordinal) %></td>
                <td><%= user.friends.count %></td>
                <td>
                  <% if user.is_friend(current_user.id) == nil %>
                    <%= link_to "Add Friend", friendships_path(:friend_id => user),
                      method: "post",
                      class: "btn btn-info btn-sm" %>
                  <% else %>
                    <%= link_to "Remvove Friend", 'friendships/' + user.is_friend(current_user.id).id.to_s,
                      method: "delete",
                      class: "btn btn-danger btn-sm" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Sign Up with GauCHAT</div>
  <div class="panel-body">

    <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <h4>Error: Invalid data. Check your inputs.</h4>
        <ul>
          <% @user.errors.full_messages.each do |thing| %>
            <li><%= thing %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for @user, :url => signup_path, :method => "post" do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, placeholder: "Name", class: "form-control", id: "user_name" %>
      </div>

      <div class="form-group">
        <label for="user_email">Email address</label>
        <%= f.email_field :email, placeholder: "Email", class: "form-control", id: "user_email" %>
      </div>
      <div class="form-group">
        <label for="user_password">Password</label>
        <%= f.password_field :password, placeholder: "Password", class: "form-control", id: "user_password" %>
      </div>

      <div class="form-group">
        <label for="user_password_confirmation">Password Confirmation</label>
        <%= f.password_field :password_confirmation, placeholder: "Password Confirmation",
              class: "form-control", id: "user_password_confirmation" %>
      </div>

      <div class="form-group form-actions text-center">
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
    <% end %>

  </div>
</div>